codse/animata

animata/text/mask-text.stories.tsx
content/docs/background/blurry-blob.mdx
content/docs/background/moving-gradient.mdx
content/docs/background/zigzag.mdx
content/docs/button/toggle-switch.mdx
content/docs/container/marquee.mdx
content/docs/container/scrolling-testimonials.mdx
content/docs/graphs/gauge-chart.mdx
content/docs/hero/shape-shifter.mdx
content/docs/image/tilted-cover.mdx
content/docs/list/avatar-list.mdx
content/docs/list/reveal-image.mdx
content/docs/text/animated-gradient-text.mdx
content/docs/text/bold-copy.mdx
content/docs/text/counter.mdx
content/docs/text/gibberish-text.mdx
content/docs/text/mask-text.mdx
content/docs/text/mirror-text.mdx
content/docs/text/swap-text.mdx
content/docs/text/text-flip.mdx
content/docs/text/wave-reveal.mdx
content/docs/widget/alarm-clock.mdx
content/docs/widget/battery-level.mdx

All necessary tailwind classes has been mentioned in order to properly render components

refactor: add necessary tailwind-config changes to the docs

---

animata/background/dot.tsx
animata/container/cursor-tracker.tsx
animata/text/mirror-text.tsx
animata/text/wave-reveal.tsx
app/_landing/faq-section.tsx
app/_landing/feature-section.tsx
app/_landing/hero-examples.tsx
app/_landing/hero-title.tsx
app/_landing/hero.tsx
app/_landing/mode-switcher.tsx
app/page.tsx
components/announcement.tsx
components/component-link-wrapper.tsx
components/site-footer.tsx

feat: update landing and link components

---

app/sitemap.ts
contentlayer.config.ts

feat: define sitemap

---

animata/text/double-underline.tsx

fix: flickering issue

---

components/sidebar-nav.tsx

fix: scroll sidebar into view if needed

---

styles/storybook.css

new style added in storybook.css
Note: there is not embedded class

 fix: resolve trailing image issue in gallery component

---

content/docs/background/blurry-blob.mdx

without this addition, the animation wouldn't have the desired effect

add instruction to update tailwind.config.js with animation key

---

animata/text/scroll-reveal.stories.tsx
animata/text/scroll-reveal.tsx
components/mdx-base-components.tsx
content/docs/text/scroll-reveal.mdx
styles/globals.css

feat: add reveal text on scroll component

---

animata/text/jitter-text.stories.tsx
animata/text/jitter-text.tsx
content/docs/text/jitter-text.mdx

feat: add Text Effect: Jitter (iMessage)

---

.gitignore
animata/text/text-explode-imessage.stories.tsx
animata/text/text-explode-imessage.tsx
content/docs/text/text-explode-imessage.mdx
tsconfig.json

feat: create text explosion effect

---

animata/text/typing-text.tsx

https://github.com/user-attachments/assets/cccd3f7c-9674-474f-9c41-edc3d4fd9192

feat: add option to hide cursor after typing the text

---

app/blog/[[...slug]]/page.tsx
app/blog/layout.tsx
app/docs/[[...slug]]/nav-menu.tsx
app/docs/[[...slug]]/page.tsx
config/blog.ts
config/docs.ts
content/blog/hacktoberfest-2024.mdx
content/blog/index.mdx
contentlayer.config.ts

Add a blog section and the hacktoberfest announcement.

feat: add blog section

---

app/_landing/newsletter.tsx
components/ui/card.tsx

This pull request fixes issue #234

Fix: Newsletter Component Updated

---

animata/card/email-feature-card.stories.tsx
animata/card/email-feature-card.tsx
content/docs/card/email-feature-card.mdx

Solve issue #222 kindly review it
feat(email-card): add feature card for email sending
Checklist: 
I have read and followed the contributing guidelines.
I have developed the component according to the requirements.
I have tested the component across different browsers and screen sizes.
I have documented the component for future reference.
I have submitted a pull request with appropriate labels and referenced this issue number.

feat(email-card): add feature card for email sending

---

CODE_OF_CONDUCT.md
animata/card/card-comment.stories.tsx
animata/card/card-comment.tsx
content/docs/card/card-comment.mdx

video 
https://www.loom.com/share/dcf56399d17f4fafb925fa4bc57f3f88
This pull request fixes #219 
I have followed proper guidelines according to the documentation . 
please check and give feed back @sudhashrestha

feat(card-comment): add card comment

---

animata/preloader/vertical-tiles.stories.tsx
animata/preloader/vertical-tiles.tsx
config/docs.ts
content/docs/preloader/vertical-tiles.mdx

Feat: added Preloader/VerticalTiles

---

README.md

Resolves #253
These changes aim to enhance the user experience and make it easier for developers to follow the documentation.

Improve README layout

---

.github/workflows/deploy.yml

fix: "chore: use head_ref"

---

animata/progress/animatedtimeline.stories.tsx
animata/progress/animatedtimeline.tsx
content/docs/progress/animatedtimeline.mdx

This PR resolves the issue #224
https://github.com/user-attachments/assets/d40fcb24-0046-468d-817d-2a34db57f3bf

PR to resolve Feature card - 009 [Automation] issue #224

---

animata/card/survey-card.stories.tsx
animata/card/survey-card.tsx
content/docs/card/survey-card.mdx

Issue #220 
Add a new component called Survey Card, which displays survey results in a card format. The component accepts an array of items, each with a vote count and item name. It also has options to set the width and title of the survey. The component is designed to be responsive and adjusts its width based on the provided width or the container's width. The survey items are displayed as bars, with the length of each bar representing the vote count. The component also includes hover effects and animations.
This commit adds the Survey Card component along with its associated story file and documentation.
demo video
https://github.com/user-attachments/assets/8bf838d4-542b-43ca-85bb-a6b2178c2380

Feature card survey

---

animata/image/images-reveal.stories.tsx
animata/image/images-reveal.tsx
content/docs/image/images-reveal.mdx

Added a new responsive component similar to Airbnb's Image Reveal Animation
Preview:
https://github.com/user-attachments/assets/57db635a-60e0-4474-918d-80a3bb653014
@sudhashrestha

feat: added airbnb type image reveal animation

---

animata/list/orbiting-items-3-d.stories.tsx
animata/list/orbiting-items-3-d.tsx
content/blog/hacktoberfest-2024.mdx
content/docs/list/orbiting-items-3-d.mdx
tailwind.config.ts

Closes #226 
- Added the Orbiting Items 3D in the "list" section of navbar 
- Updated the docs file for the same component 
Please review my request..and suggest any changes needed..ready to improvise if necessary..

Added the Orbiting items 3D components

---

animata/fabs/speed-dial.stories.tsx
animata/fabs/speed-dial.tsx
config/docs.ts
content/docs/fabs/speed-dial.mdx

Added Speed Dial Component addressing issue #316
https://github.com/user-attachments/assets/f0328be5-6aa5-4701-850e-e694b3fccf55

feat:(FABs) add Customizable speed dial with a tooltip #316

---

animata/accordion/faq.stories.tsx
animata/accordion/faq.tsx
config/docs.ts
content/docs/accordion/faq.mdx

created the faq section!
https://github.com/user-attachments/assets/d60e4a90-035b-44aa-8f2b-a59585d646ac

feat(faq-section): add faq in accordion

---

animata/widget/fund-widget.stories.tsx
animata/widget/fund-widget.tsx
content/docs/widget/fund-widget.mdx

-Added fund widget in the widget section
-Modified the docs file
-Modified the stories file

feat(#329): added the fund Widget

---

animata/feature-cards/content-scan.stories.tsx
animata/feature-cards/content-scan.tsx
content/docs/feature-cards/content-scan.mdx
tailwind.config.ts

fixes: #310
preview: https://www.loom.com/share/ec71320b8ac646dea2f58e7fb7784209
Added content scan component which takes arguments as the whole content and the detected words array and scanning duration (default 3 sec) and reverse animation duration (default 1 sec).

fix: added content scan component

---

animata/list/flower-menu.stories.tsx
animata/list/flower-menu.tsx
content/docs/list/flower-menu.mdx

This PR introduces a new `flower-menu` component, which displays a circular flower menu with several icons and a central close button.
The component features a responsive layout and interactive elements to enhance user experience.
https://github.com/user-attachments/assets/02ee2c11-ad8e-48fc-826b-37bba4eb5fb9
- Responsive design that adapts to various screen sizes
- Interactive hover effects for improved user feedback
- Clean and modern UI using Tailwind CSS classes
- Efficient rendering of multiple time zones
Please review and let me know if any changes or additional information is needed.

feat: implement flower menu component

---

content/docs/section/pricing.mdx

docs(pricing-component): fix typo

---

animata/accordion/faq.stories.tsx
animata/accordion/faq.tsx
animata/widget/calendar-widget.stories.tsx
animata/widget/calendar-widget.tsx
config/docs.ts
content/docs/accordion/faq.mdx
content/docs/widget/calendar-widget.mdx

This PR introduces a new Calendar Widget, which looks like an calendar and shows dates and events dynamically with smooth animations 
https://github.com/user-attachments/assets/ea62e1e2-3b43-405f-a3da-dfda24471d5b

Calendar widget  (issue #321)
